
name: askcos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.8
  - celery=4.4
  - cython=0.29.21
  - h5py=2.10.0
  - hdbscan=0.8.23
  - jupyter
  - keras=2.2.4
  - markdown
  - matplotlib=3.3.0
  - networkx=2.4
  - numpy=1.19.1
  - pandas=1.1.0
  - pango=1.42.4
  - pillow=7.2.0
  - pip
  - pycairo=1.19.1
  - pymongo=3.10.1
  - pytorch>=1.4
  - pyyaml=5.3.1
  - rdkit=2020.03.6
  - requests
  - scipy=1.5.2
  - scikit-learn=0.23.1
  - sphinx
  - tensorflow=2.0.0
  - tensorflow-estimator=2.0.0
  - tqdm
  - cairosvg=2.4.2
  - pip:
      - rdchiral